version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./src/.env
    depends_on:
      - redis
      - postgres
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  
  postgres:
    image: "postgres:14-alpine"
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/models/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: